name: re_editor
description: Re-Editor is a powerful lightweight text and code editor component.
version: 0.0.1
homepage: https://reqable.com
repository: https://github.com/reqable/reqable-editor

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  re_highlight: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  path: ^1.8.2